name: CI for Node JS
 
on:
   push: 
       branches: ["donal"]
jobs:
   build:
       runs-on: ubuntu-latest
       strategy:
        matrix:
           node-version: [18.x, 19.x,20.x]
       steps:
        - name: Check Repository
          uses: actions/checkout@v4
        
        - name: Use Node ${{ matrix.node-version }}
          uses: actions/setup-node@v4 
          with:
            node-version: ${{matrix.node-version}}
            cache: 'npm'